/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Planificador.Planning;
import Componentes.ListaDoble;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import sun.awt.windows.ThemeReader;

/**
 *
 * @author diego
 */
public class Threads extends javax.swing.JPanel {

    /**
     * Creates new form Hilos
     */
     String nombre;
    int cont=0;
    ListaDoble listaDoble=new ListaDoble();
    Planning f=new Planning(listaDoble);
    
    public Threads(int cont,ListaDoble listaDoble) {//ordenar procesos insertados y simular preocesos
        initComponents();
        this.setOpaque(true);
        this.setSize(new Dimension(3000,20));
        this.setBackground(Color.WHITE);
        this.cont=cont;
        this.listaDoble=listaDoble;
    }
    
     public void paint(Graphics g){//dibujar los nodos
    super.paint(g);
    g.setColor(Color.white);
        g.setColor(Color.BLUE);
        
        int disNodo = 50,aumentoNodo = 120;
        
        int disNombre = 77,aumentoNombre=120;
        
        for (int i = 0; i < cont; i++) {
        
            //g.drawImage(img.getImage(), disNodo, 35, 170, 50, this);
            g.setColor(Color.BLUE);
            g.fillRect(disNodo, 80, 100, 50);
            disNodo += aumentoNodo;
            
            this.setSize(disNodo+200, 21);
                                    
            g.setColor(Color.WHITE);
            g.drawString(listaDoble.get(i).dato.getNombre(), disNombre, 100);
            
//            g.setColor(Color.orange);
//            g.drawString(String.valueOf(tiempoespera), disNombre, 190);
            this.repaint();

            disNombre += aumentoNombre;
        
            
            
        }
        disNombre=50;
        aumentoNombre=115;
            int t = 0;
            double r=0;
            int tiempoespera=0;
            for(int j=0;j<listaDoble.size();j++){
                if(j==0){
                  tiempoespera+=listaDoble.get(j).dato.getRafaga()+listaDoble.get(j).dato.getTiempo();
                  t=listaDoble.get(j).dato.getTiempo();
                  g.setColor(Color.BLACK);
                  g.drawString(String.valueOf(t), disNombre, 150);
                }else{
                    g.setColor(Color.BLACK);
                    g.drawString(String.valueOf(tiempoespera), disNombre, 150);
                    tiempoespera+=listaDoble.get(j).dato.getRafaga();
                }  
                disNombre += aumentoNombre;
            }
        g.setColor(Color.BLACK);
        g.drawString(String.valueOf(tiempoespera), disNombre, 150);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
